apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.acme.id }}
  labels:
  {{- include "acme.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.acme.email }}
    server: {{ .Values.acme.server }}
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: {{ .Values.acme.id }}
    solvers:
  {{- toYaml .Values.acme.solvers | nindent 6 }}