{{- if .Values.pritunl.mongodbUri -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pritunl.fullname" . }}
type: Opaque
stringData:
  mongodb-uri: {{ .Values.pritunl.mongodbUri }}
{{- end -}}
