# Default values for acme.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

acme:
  id: "letsencrypt-prod"
  email: ""
  server: "https://acme-v02.api.letsencrypt.org/directory"

  solvers:
    - http01:
        ingress:
          class: traefik